// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8nzCTV8kUBLDkG3CazJ_y3cvfO2spqbQ',
    appId: '1:222641521093:web:59164089497118123f0bac',
    messagingSenderId: '222641521093',
    projectId: 'fir-flutter-codelab-b9813',
    authDomain: 'fir-flutter-codelab-b9813.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-b9813.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo3_5jM_zauz5kCw6tIjbmu5cYzaUf9q4',
    appId: '1:222641521093:android:3102c2d9f33c78fd3f0bac',
    messagingSenderId: '222641521093',
    projectId: 'fir-flutter-codelab-b9813',
    storageBucket: 'fir-flutter-codelab-b9813.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHuNMP3psXzmnFCC1XWhvd5xI4DZxCi_U',
    appId: '1:222641521093:ios:a7839da83cdd5bb43f0bac',
    messagingSenderId: '222641521093',
    projectId: 'fir-flutter-codelab-b9813',
    storageBucket: 'fir-flutter-codelab-b9813.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHuNMP3psXzmnFCC1XWhvd5xI4DZxCi_U',
    appId: '1:222641521093:ios:a7839da83cdd5bb43f0bac',
    messagingSenderId: '222641521093',
    projectId: 'fir-flutter-codelab-b9813',
    storageBucket: 'fir-flutter-codelab-b9813.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8nzCTV8kUBLDkG3CazJ_y3cvfO2spqbQ',
    appId: '1:222641521093:web:7562908dce4a57483f0bac',
    messagingSenderId: '222641521093',
    projectId: 'fir-flutter-codelab-b9813',
    authDomain: 'fir-flutter-codelab-b9813.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-b9813.appspot.com',
  );
}
